// data is an array of objects, each object is a product has the common characteristics: type, name, brand, cost, img (source image, this is the array string), infor (information)
// proNo, availability, details (this is the object, separate sections of each product)

var data = [
	// Hard drive
	{	
		type : "hard drives",
		name : "Toshiba Canvio HDTB310EK3AA Hard Drive", 
		brand : "Toshiba",
		cost : "42.85",
		img : ["image/Toshiba-Canvio Basics 1TB Portable External Hard Drive.jpg" ,"image/Toshiba-Canvio Basics 1TB Portable External Hard Drive2.jpg" , "image/Toshiba-Canvio Basics 1TB Portable External Hard Drive3.jpg"],
		info : [ '2.5 " external hard drive' , '500 GB / 1 TB / 2 TB / 3 TB capacity' ,'High speed USB 3.0 port','Ideal add-on storage for your PC, Xbox One or PS4'],
		proNo : "HDTB310EK3AA",
		availability : "In Stock",
		detail : {
			"Rate" : "4",
			"Brand name" : "Toshiba",
			"Item Weight"	: "127g",
			"Product Dimensions" : "11.9 x 7.9 x 1.5 cm ",
			"Item model number" : "HDTB310EK3AA",
			"Hard Drive Size": "1 TB",
			"Hard Drive Interface" : "	Serial ATA-300",
			"Number of USB 2.0 Ports" : "1",
			Color : "Black",
			"Software Included" : "Windows 8.1 x64",
			Asin : "B00KWHJY7Q",
			"Date First Available" : "10 Jun. 2014",
		}

	},
	{
		type : "hard drives",
		name : "Toshiba Canvio HDTC810EK3AA Hard Drive",
		brand : "Toshiba",
		cost : "49.92" ,
		img : ["image/Toshiba-Canvio Connect II 1TB Portable External Hard Drive 25 Inch USB 3.jpg","image/Toshiba-Canvio Connect II 1TB Portable External Hard Drive 25 Inch USB 32.jpg","image/Toshiba-Canvio Connect II 1TB Portable External Hard Drive 25 Inch USB 33.jpg"],
		info : ["Portable external hard drive with 1TB capacity","Ultra fast transfer speeds with USB 3.0 (USB 2.0 compatible)","Auto-backup software","NTFS driver for Mac included"],
		proNo : "HDTC810EK3AA",
		availability : "From the Sellers",
		detail : {
			"Rate" : "4.4",
			"Brand name" : "Toshiba",
			"Item Weight" : "163g",
			"Product Dimensions" : "7.8 x 10.9 x 1.4 cm",
			"Item model number" : "HDTC810EK3AA",
			"Hard Drive Size" : "1TB",
			"Hard Drive Interface" : "USB 3.0",
			"Number of USB 2.0 Ports" : "1",
			Color : "Black",
			"Software Included" : "Mac OS X 10.9 Mavericks",
			Asin : "B00TB7K95Y",
			"Date First Available" : "5 Feb. 2015"
		}
	},
	{
		type : "hard drives",
		name : "Toshiba Canvio HDTH310EK3AA Hard Drive",
		brand : "Toshiba",
		cost : "42.00" ,
		img : ["image/Toshiba Canvio Alu 1TB Portable External Hard Drive 2.5 Inch USB 3.0.jpg","image/Toshiba Canvio Alu 1TB Portable External Hard Drive 2.5 Inch USB 3.02.jpg","image/Toshiba Canvio Alu 1TB Portable External Hard Drive 2.5 Inch USB 3.03.jpg"],
		info : ["Portable external hard drive with 1TB capacity","Ultra fast transfer speeds with USB 3.0 (USB 2.0 compatible)","Auto-backup software on-board","Durable protection with sleek and solid aluminium casing","500GB, 1TB & 2TB capacities"],
		proNo : "HDTH310EK3AA",
		availability : "From the Sellers",
		detail : {
			"Rate" : "4.9",
			"Brand name" : "Toshiba",
			"Item Weight" : "200g",
			"Product Dimensions" : "11.4 x 1.2 x 7.1 cm",
			"Item model number" : "HDTH310EK3AA",
			"Hard Drive Size" : "1TB",
			"Hard Drive Interface" : "USB 3.0",
			"Number of USB 2.0 Ports" : "1",
			Color : "Black",
			"Software Included" : "Mac OS X 10.9 Mavericks",
			Asin : "B00MA3LJ6O",
			"Date First Available" : "3 Aug. 2014",
		}
	},
	{	
		type : "hard drives",
		name : 'Toshiba P300 500GB 7200RPM 3.5"',
		brand : "Toshiba",
		cost : "32.98",
		img : ["image/Toshiba P300 500GB.jpg",'image/Toshiba P300 500GB2.jpg',"image/Toshiba P300 500GB3.jpg"],
		info : ["High performance, reliable internal hard drive","Data protection technology","Temperature (operating / non-operating) : 0 to 65 degree celsius / -40 to 70 degree celsius","Perfect for challenging applications including gaming and photo/video editing"],
		proNo : "HDWD105UZSVA",
		availability : "In Stock",
		detail : {
			"Rate" : "4.6",
			"Brand name" : "Toshiba",
			"Item Weight" : "449g",
			"Product Dimensions" : "14.7 x 10.1 x 2.6 cm",
			"Item model number" : "HDWD105UZSVA",
			"Hard Drive Size" : "500 GB",
			"Hard Drive Interface" : "Serial ATA-600",
			"Number of USB 2.0 Ports" : "1",
			Color : "Black",
			"Software Included" : "Mac OS X 10.9 Mavericks",
			Asin : "B0151KM1WS",
			"Date First Available" : "9 Sept. 2015",
		}
	}, 

	// usb
	{	
		type : "usb",
		name : "Lenovo USB Type-C to 4 Port USB 3.0 Hub",
		brand : "Lenovo",
		cost : "13.99",
		img : [ "image/Lenovo USB Type-C to 4 Port USB 3.0 Hub, Aluminum USB2.jpg", "image/Lenovo USB Type-C to 4 Port USB 3.0 Hub, Aluminum USB.jpg","image/Lenovo USB Type-C to 4 Port USB 3.0 Hub, Aluminum USB3.jpg"],
		info : ["Tarnsforms a computer's Type-C port into 4 individual USB 3.0 ports","High-Speed USB 3.0 Port: USB 3.0 port provides 5 Gbps transfer speeds, which are 10X faster than USB 2.0","Aluminium Design: Aluminium alloy design matches your low profile laptop perfectly","Easy to carry: Extremely compact design makes it easily portable and travel-friendly"],
		proNo : "C610",
		availability : "In Stock",
		detail : {
			"Rate" : "4.8",
			"Brand name" : "Lenovo",
			"Item Weight" : "99.8 g",
			"Product Dimensions" : "11.2 x 3.2 x 0.9 cm",
			"Item model number" : "C610",
			Color : "white",
			Asin : "B076BMBMCW",
			"Shipping Weight" : "112 g",
			"Date First Available" : "9 Oct. 2017",
		}

	},
	{	
		type : "usb",
		name : "Lenovo USB C Hub with Ethernet Port",
		brand : "Lenovo",
		cost : "20.49 ",
		img : [ "image/Lenovo USB C Hub with Ethernet Port, Type C Adapter with 3 USB 3.0 Ports.jpg", "image/Lenovo USB C Hub with Ethernet Port, Type C Adapter with 3 USB 3.0 Ports2.jpg","image/Lenovo USB C Hub with Ethernet Port, Type C Adapter with 3 USB 3.0 Ports3.jpg"],
		info : ["Instant Expansion with 4 Ports: Transforms a computer's Type-C","RJ-45 Gigabit Ethernet Port gives you access to superfast network speed","High-Speed USB 3.0 Port: USB 3.0 port provides 5 Gbps transfer speeds, which are 10X faster than USB 2.0","Plug and Play: Does not require any software, drivers, or complicated installation process"],
		proNo : "C506",
		availability : "In Stock",
		detail : {
			"Rate" : "4.9",
			"Brand name" : "Lenovo",
			"Item Weight" : "49.9 g",
			"Product Dimensions" : "9.2 x 4.1 x 1.3 cm",
			"Item model number" : "C506",
			Color : "Grey",
			Asin : " B0761QWYHG",
			"Shipping Weight" : "52g",
			"Date First Available" : "28 Sept. 2017",
		}
	},
	{	
		type : "usb",
		name : "USB-C to HDMI, Benfei USB C Digital",
		brand : "Benfei",
		cost : "49.99",
		img : [ "image/BENFEI-USB-C Digital AV Multiport Adapter, BENFEI USB 3.1 Type-C.jpg", "image/BENFEI-USB-C Digital AV Multiport Adapter, BENFEI USB 3.1 Type-C2.jpg","image/BENFEI-USB-C Digital AV Multiport Adapter, BENFEI USB 3.1 Type-C3.jpg"],
		info : ["Compatible with Apple 2017 2016 (2015) New MacBook 12in 15in","POWER DELIVERY: Charging your laptop while connecting multiple peripherals "," Mirror or extend your screen with the HDMI port and directly stream 4K UHD or Full HD 1080p video to HDTV","High Speed Ethernet: Supporting 10/100 /1000Mbps bandwidth Ethernet."],
		proNo : "000148silver",
		availability : "In Stock",
		detail : {
			"Rate" : "4.3",
			"Brand name" : "BENFEI",
			"Item Weight" : "27.2 g",
			"Product Dimensions" : "9.2 x 4.1 x 1.3 cm",
			"Item model number" : "000148silver",
			Color : "Grey",
			Asin : " B073W96K4J",
			"Shipping Weight" : "28g",
			"Date First Available" : "10 July 2017",
		}
	},
	{
		type : "usb",
		name : "USB VGA Adapter, Benfei",
		brand : "Benfei",
		cost : "9.85 ",
		img : [ "image/USB Type C(Thunderbolt 3) to VGA Adapter, Benfei USB 3.1 (USB-C) to VGA Adapter Male to Female.jpg", "image/USB Type C(Thunderbolt 3) to VGA Adapter, Benfei USB 3.1 (USB-C) to VGA Adapter Male to Female2.jpg","image/USB Type C(Thunderbolt 3) to VGA Adapter, Benfei USB 3.1 (USB-C) to VGA Adapter Male to Female3.jpg"],
		info : ["USB-C & THUNDERBOLT 3 port compatible with computers and video over USB equipped smartphones such as 2016 Macbook Pro, the 2015 MacBook, ASUS ROG G752 ,MSI GS40 , and Razor Blade Sheath","Supports video resolutions up to 1920*1200@60Hz (HD)","Plug in and play, no need any software installation or configuration"],
		proNo : "000136Grey",
		availability : "In Stock",
		detail : {
			"Rate" : "4.5",
			"Brand name" : "BENFEI ",
			"Item Weight" : "40.8 g",
			"Product Dimensions" : "20 x 5 x 2 cm",
			"Item model number" : "000136Grey",
			Color : "Grey",
			Asin : " B071CQ342W",
			"Shipping Weight" : "41.8g",
			"Date First Available" : "10 April 2017",
		}
	},
	{	
		type : "usb",
		name : "Benfei USB C to USB 3.0 Adapter",
		brand : "Benfei",
		cost : "9.85 ",
		img : [ "image/Benfei USB C to USB 3.0 Adapter and USB Type C to Micro USB.jpg", "image/Benfei USB C to USB 3.0 Adapter and USB Type C to Micro USB2.jpg","image/Benfei USB C to USB 3.0 Adapter and USB Type C to Micro USB3.jpg"],
		info : ["Connects USB-A (flash drives, keyboards, mice) to USB-C devices (smartphones, tablets, laptops)","USB-C to Micro USB Adapter allows you to charge and sync USB-C devices with a micr0","Supports USB OTG - Plug in and use computer peripherals like a keyboard, hub, or mouse with your USB-C","Package Contents: 1 Benfei USB-C to Benfei USB Type C to Micro USB Female Adapter"],
		proNo : "000141Grey",
		availability : "In Stock",
		detail : {
			"Rate" : "4.9",
			"Brand name" : "BENFEI",
			"Item Weight" : "4.5 g",
			"Product Dimensions" : "20 x 5 x 2 cm",
			"Item model number" : "000141Grey",
			Color : "Grey",
			Asin : " B071PBSSPW",
			"Shipping Weight" : "7g",
			"Date First Available" : "26 May 2017",
		}
	},
	{
		type : "usb",	
		name : "Acer Mini Converter USB 2.0",
		brand : "Acer",
		cost : "32.72",
		img : [ "image/Acer Mini Converter Port Cable.jpg", "image/Acer Mini Converter Port Cable2.jpg","image/Acer Mini Converter Port Cable3.jpg"],
		info : ["Compatible with Aspire V5 and R7 series","Input: mini display, outputs: RJ45, USB 2.0, VGA","Box contents: Acer mini converter port cable to VGA, RJ45, USB 2.0 - Black","Connects notebook to cables with RJ-45 connectors, external monitors, displays or projectors with VGA connector or cable"],
		proNo : "P.OTH11.00CN",
		availability : "In Stock",
		detail : {
			"Rate" : "4.1",
			"Brand name" : "Acer",
			"Item Weight" : "4.9 g",
			"Product Dimensions" : "27.7 x 18.1 x 2.4 cm",
			"Item model number" : "P.OTH11.00CN",
			Color : "Black",
			Asin : " B00DG6UUC8",
			"Shipping Weight" : "8g",
			"Date First Available" : "2 Oct. 2013",
		}
	},
	// Keyboards
	{	
		type : "keyboards",
		name : "Corsair K70 Mechanical Gaming Keyboard",
		brand : "Corsair",
		cost : "85.44",
		img : [ "image/Corsair K70 LUX RGB Mechanical Gaming Keyboard.jpg", "image/Corsair K70 LUX RGB Mechanical Gaming Keyboard2.jpg","image/Corsair K70 LUX RGB Mechanical Gaming Keyboard3.jpg"],
		info : ["Aircraft-grade anodized brushed aluminium frame for superior durability", "Advanced lighting control and large font keycaps deliver dynamic, vibrant backlighting","CUE support enables advanced macro and lighting programming for virtually unlimited game customisation", "100 Percent anti-ghosting with full key rollover on USB"],
		proNo : "CH-9101021-UK",
		availability : "In Stock",
		detail : {
			"Rate" : "4.6",
			"Brand name" : "Corsair",
			"Item Weight" : "1.2 Kg",
			"Product Dimensions" : "43.6 x 16.5 x 3.8 cm",
			"Item model number" : "CH-9101021-UK",
			Color : "Black",
			Asin : " B01LLEFW9M",
			"Number of USB 2.0 Ports" : "2",
			"Shipping Weight" : "1.3 kg",
			"Date First Available" : "5 Sept. 2016",
		}	
	},
	{	
		type : "keyboards",
		name : "Corsair K95 RGB Gaming Keyboard",
		brand : "Corsair",
		cost : "179.98",
		img : [ "image/Corsair K95 Platinum RGB Mechanical Gaming Keyboard.jpg", "image/Corsair K95 Platinum RGB Mechanical Gaming Keyboard2.jpg","image/Corsair K95 Platinum RGB Mechanical Gaming Keyboard3.jpg"],
		info : ["Aircraft-grade anodized brushed aluminium frame","8MB profile storage with hardware macro ","Dynamic multicolour per key backlighting with Light Edge", "100% CHERRY MX Speed RGB mechanical key switches","6 programmable G-keys keys for in-game macros"],
		proNo : "CH-9121021-UK",
		availability : "In Stock",
		detail : {
			"Rate" : "4.2",
			"Brand name" : "Corsair",
			"Item Weight" : "998 g",
			"Product Dimensions" : "46.5 x 17.1 x 3.6 cm",
			"Item model number" : "CH-9121021-UK",
			Asin : " B01N9OIRSD",
			Color : "Black",
			"Number of USB 2.0 Ports" : "2",
			"Shipping Weight" : "1.3 kg",
			"Date First Available" : "5 Jan. 2017",

		}
	},
	{
		type : "keyboards",
		name : "Lenovo Keyboard FOR Thinkpad L410",
		brand : "Lenovo ",
		cost : "65.00" ,
		img : [ "image/Lenovo Keyboard FOR Thinkpa Keyboard.jpg", "image/Corsair K95 Platinum RGB Mechanical Gaming Keyboard2.jpg","image/Corsair K95 Platinum RGB Mechanical Gaming Keyboard3.jpg"],
		info : ["Aircraft-grade anodized brushed aluminium frame","8MB profile storage with hardware macro and lighting playback","Dynamic multicolour per key backlighting with Light Edge", "100% CHERRY MX Speed RGB mechanical key switches"],
		proNo : "45N2365",
		availability : "In Stock",
		detail : {
			"Rate" : "4.9",
			"Brand name" : "Lenovo",
			"Item Weight" : "281 g",
			"Product Dimensions" : "38 x 24 x 4.6 cm",
			"Item model number" : "45N2365",
			Color : "Black",
			Asin : " B01N9OIRSD",
			"Number of USB 2.0 Ports" : "2",
			"Shipping Weight" : "300 g",
			"Date First Available"	 : "17 Mar. 2011",
		}
	},
	{
		type : "keyboards",
		name : "Corsair K63 Mechanical Gaming ",
		brand : "Corsair",
		cost : "64.99",
		img : ["image/Corsair K63 Mechanical Gaming.jpg","image/Corsair K63 Mechanical Gaming2.jpg","image/Corsair K63 Mechanical Gaming3.jpg"],
		info : ["100% CHERRY MX Red mechanical key switches with gold contacts for fast, precise key presses","Per-key, red LED backlighting and large font keycaps deliver vibrant lighting effects","Compact, ten keyless design for optimizing desk space and mobility","Tenkeyless design eliminates keypad area"],
		proNo : "CH-9115020-UK",
		availability : "In Stock",
		detail : {
			"Rate" : "4.7",
			"Brand name" : "Corsair",
			"Item Weight" : "998g",
			"Product Dimensions" : "	36.5 x 17.1 x 4.1 cm",
			"Item model number" : "CH-9115020-UK",
			Color : "Black",
			Asin : " B06XQ5G9ZZ",
			"Number of USB 2.0 Ports" : "2",
			"Shipping Weight" : "300 g",
			"Date First Available" : "17 Mar. 2017",
		}
	},
	// laptop
	{
		type : "laptop",
		name : "Acer Chromebook 14 CB3-431 Notebook",
		brand : "Acer",
		cost : "239.99",
		img : ["image/Acer Chromebook 14 CB3-431 14-Inch Notebook.jpg","image/Acer Chromebook 14 CB3-431 14-Inch Notebook2.jpg","image/Acer Chromebook 14 CB3-431 14-Inch Notebook3.jpg"],
		info : ["All aluminium alloy housing. Need we say more? Possessed of style, strength and durability, our Chromebook 14 will go the distance and back again","As thin, compact and light as the Chromebook 14 is, IPS technology and a low reflection anti-glare screen.","Enjoy fast wireless internet speeds with dual-band MIMO technology and 802.11ac technology."],
		proNo : "NX.GC2EK.003",
		availability : "In Stock",
		detail : {
			"Rate" : "4.66",
			"Brand name" : "Acer",
			"Item Weight" : "1.55 Kg",
			"Product Dimensions" : "23.6 x 34.1 x 1.7 cm",
			"Item model number" : "NX.GC2EK.003",
			"Screen Resolution" : "1366 x 768 pixels",
			"RAM Size" : "2 GB",
			"Computer Memory Type" : "DDR4 SDRAM",
			"Hard Drive Size" : "32 GB",
			"Graphics Card Description" : "HD Graphics 400",
			"Lithium Battery Energy Content" : "45 watt_hours",
			Color : "Sliver",
			Asin : " B06XQ5G900",
			"Shipping Weight" : "2.4kg",
			"Date First Available" : "17 Mar. 2017",
		}

	},
	{
		type : "laptop",
		name : "Lenovo IdeaPad 320-14IKBN HD Notebook",
		brand : "Lenovo",
		cost : "450.16 ",
		img : ["image/Lenovo IdeaPad 320-14IKBN 14-Inch HD Notebook.jpg","image/Lenovo IdeaPad 320-14IKBN 14-Inch HD Notebook2.jpg","image/Lenovo IdeaPad 320-14IKBN 14-Inch HD Notebook3.jpg"],
		info : ["<Pro></Pro>cessor: Intel 7th Gen Intel Core I3-7100U, 3M Cache, 2.40 GHz","Internal Memory: 4G DDR4 2133 ONBOARD RAM","Storage: 128 GB SATA SSD","Display Type: 14'' HD (1366 x 768)","Operating System: Windows 10 Home 64"],
		proNo : "80XK0103UK",
		availability : "In Stock",
		detail : {
			"Rate" : "4.96",
			"Brand name" : "Lenovo",
			"Item Weight" : "1.5 Kg",
			"Product Dimensions" : "22 x 32 x 4 cm",
			"Item model number" : "80XK0103UK",
			"Screen Resolution" : "1366 x 768 pixels",
			"RAM Size" : "4 GB",
			"Computer Memory Type" : "DDR4 SDRAM",
			"Hard Drive Size" : "128 GB",
			"Graphics Card Description" : "HD Graphics 620",
			"Lithium Battery Energy Content" : "40 watt_hours",
			Color : "Platinum",
			Asin : " B07515ZHV9",
			"Shipping Weight" : "2.2kg",
			"Date First Available" : "15 Dec. 2017",
		}		
	},
	{
		type : "laptop",
		name : "Lenovo IdeaPad 320S 14.0'' HD Laptop",
		brand : "Lenovo",
		cost : "349.99",
		img : ["image/Lenovo IdeaPad 320S 14.0 HD Laptop.jpg","image/Lenovo IdeaPad 320S 14.0 HD Laptop2.jpg","image/Lenovo IdeaPad 320S 14.0 HD Laptop3.jpg"],
		info : ["Premium aluminium finish & minimalist design - The Ideapad 320S 14' is stylishly sleek, and surprisingly portable","Ample storage for all your needs","Streamline your day with Windows 10 Home"],
		proNo : "80X4001UUK",
		availability : "In Stock",
		detail : {
			"Rate" : "4.89",
			"Brand name" : "Lenovo",
			"Item Weight" : "1.69 Kg",
			"Product Dimensions" : "32.7 x 23.6 x 1.9 cm",
			"Item model number" : "80X4001UUK",
			"Screen Resolution" : "1366 x 768 pixels",
			"RAM Size" : "4 GB",
			"Computer Memory Type" : "DDR3 SDRAM",
			"Hard Drive Size" : "128 GB",
			"Graphics Card Description" : "HD Graphics 610",
			"Lithium Battery Energy Content" : "30 watt_hours",
			Color : "White",
			Asin : " B078YTTF7H",
			"Shipping Weight" : "2.1kg",
			"Date First Available" : "3 Jan. 2018",
		}
	},
	{
		type : "laptop",
		name : "Acer Swift SF113-31-P52E Notebook",
		brand : "Acer",
		cost : "349.99",
		img : ["image/Acer Swift SF113-31-P52E Ultrabook 13.3-Inch Notebook.jpg","image/Acer Swift SF113-31-P52E Ultrabook 13.3-Inch Notebook2.jpg","image/Acer Swift SF113-31-P52E Ultrabook 13.3-Inch Notebook3.jpg"],
		info : ["The vogue look of the Swift 1 is matched only by the convenience of its thin, easily portable design.","Type comfortably anytime with the Swift 1's elegant, new backlit keyboard","Share the screen and its true colours with your friends using the high-definition IPS display."],
		proNo : "NX.GNLEK.002",
		availability : "In Stock",
		detail : {
			"Rate" : "4.8",
			"Brand name" : "Acer",
			"Item Weight" : "1.3 Kg",
			"Product Dimensions" : "22.5 x 32 x 1.5 cm",
			"Item model number" : "NX.GNLEK.002",
			"Screen Resolution" : "1920 x 1080 pixels",
			"RAM Size" : "4 GB",
			"Computer Memory Type" : "DDR3 SDRAM",
			"Hard Drive Size" : "128 GB",
			"Graphics Card Description" : "HD Graphics 505",
			"Lithium Battery Energy Content" : "42 watt_hours",
			Color : "Pure Silver",
			Asin : " B076661HS9",
			"Shipping Weight" : "2.2kg",
			"Date First Available" : "4 Oct. 2017",
		}
	},
	{
		type : "laptop",
		name : "ASUS S510UQ-BQ178T VivoBook",
		brand : "Asus",
		cost : "610.99",
		img : ["image/ASUS S510UQ-BQ178T VivoBook.jpg","image/ASUS S510UQ-BQ178T VivoBook2.jpg","image/ASUS S510UQ-BQ178T VivoBook3.jpg"],
		info : ["Ultra-thin metal chassis at just 17.9 mm thick","80% screen to body ratio, with ultra slim bezel for better viewing experience","Dedicated Nvidia GeForce GT940MX 2 GB graphics","Powered by Intel's 7th Generation i5 processor"],
		proNo : "S510UQ-BQ178T",
		availability : "Available from these sellers.",
		detail : {
			"Rate" : "4.8",
			"Brand name" : "Asus",
			"Item Weight" : "2 Kg",
			"Product Dimensions" : "24 x 36 x 1.7 cm",
			"Item model number" : "S510UQ-BQ178T",
			"Screen Resolution" : "1920 x 1080 pixels",
			"RAM Size" : "8 GB",
			"Computer Memory Type" : "GDDR5",
			"Hard Drive Size" : "256 GB",
			"Graphics Card Description" : "Nvidia GTX940MX",
			"Lithium Battery Energy Content" : "42 watt_hours",
			Color : "Gold",
			Asin : " B073WHY9SG",
			"Shipping Weight" : "2.8 kg",
			"Date First Available" : "8 Jun. 2017",
		}
	},
	//display
	{
		type : "display",
		name : "Acer S241HL BMID Monitor",
		brand : "Acer",
		cost : "109.99",
		img : ["image/Acer S241HL BMID Monitor.jpg","image/Acer S241HL BMID Monitor2.jpg","image/Acer S241HL BMID Monitor3.jpg"],
		info : ["1920 x 1080 resolution, slim LED design, with built-in speakers.","Acer ultra-thin monitors are designed for users who have limited space to work with, be it at home, a public area or front-desk setting.","Quick 5ms response time reduces deviations in transition time to deliver high-quality moving images"],
		proNo : "S241HL bmid",
		availability : "In Stock",
		detail : {
			"Rate" : "4.84",
			"Brand name" : "Acer",
			"Item Weight" : "7.6 pounds",
			"Product Dimensions" : "22.2 x 6.5 x 15.8 inches",
			"Item model number" : "S241HL bmid",
			"Screen Size" : "24 inches",
			"Screen Resolution" : "1920 x 1080 pixels",
			Color : "Black",
			Asin : " B00CBNIXHQ",
			"Shipping Weight" : "11.4 pounds",
			"Date First Available" : "4 Aprill. 2017",
		}
	},
	{
		type : "display",
		name : "Acer V246HQL LCD Monitor",
		brand : "Acer",
		cost : "99.99",
		img : ["image/Acer V246HQL LCD Monitor.jpg","image/Acer V246HQL LCD Monitor2.jpg","image/Acer V246HQL LCD Monitor3.jpg"],
		info : ["23.6-Inch Full HD (1920 x 1080)","Brightness: 250 cd/m2","Viewing Angle: ANGLE: 170(H) X 160(V)","Stand: TILT, Detachable Foot Stand,"],
		proNo : "K242HQLBBMD",
		availability : "In Stock",
		detail : {
			"Rate" : "4.81",
			"Brand name" : "Acer",
			"Item Weight" : "8.7 pounds",
			"Product Dimensions" : "24.4 x 16.5 x 5 inches",
			"Item model number" : "K242HQLBBMD",
			"Screen Size" : "24 inches",
			"Screen Resolution" : "1920 x 1080 pixels",
			Color : "Black",
			Asin : " B011QXHNZY",
			"Shipping Weight" : "10.45 pounds",
			"Date First Available" : "4 Aprill. 2015",
		}
	},
	{
		type : "display",
		name : "Sam sung LC49HG9 Gaming Monitor",
		brand : "Sam sung",
		cost : "901.17",
		img : ["image/Sam sung LC49HG90DMNXZA Gaming Monitor.jpg","image/Sam sung LC49HG90DMNXZA Gaming Monitor2.jpg","image/Sam sung LC49HG90DMNXZA Gaming Monitor3.jpg"],
		info : ["49-inch monitor with super ultra-wide 49-inch screen with its innovative 32:9 aspect ratio","Samsung QLED delivers purer, brighter","Designed for Gamers with Multiple Game Modes","Kindly use the link in the User Manual to Update the system software"],
		proNo : "LC49HG90DMNXZA",
		availability : "In Stock",
		detail : {
			"Rate" : "4.89",
			"Brand name" : "Sam sung",
			"Item Weight" : "33.1 pounds",
			"Product Dimensions" : "47.4 x 15 x 20.7 inches",
			"Item model number" : "LC49HG90DMNXZA",
			"Screen Size" : "49 inches",
			"Screen Resolution" : "3840 X 1080 pixels",
			Color : "Black",
			Asin : " B072C7TNC5",
			"Shipping Weight" : "45 pounds",
			"Date First Available" : "9 June 2017",
		}	
	},
	{
		type : "display",
		name : "Sam sung Curved Gaming Monitor",
		brand : "Sam sung",
		cost : "420.19",
		img : ["image/Sam sung Curved Gaming Monitor.jpg","image/Sam sung Curved Gaming Monitor2.jpg","image/Sam sung Curved Gaming Monitor3.jpg"],
		info : ["Quantum dot","1 billion color support","Refresh rate 144Hz;Response time 1M/s","Product Dimensions With Stand:24.60 x 21.92 x 15.38 inches,Product Dimensions Without Stand:24.60 x 14.46 x 3.67 inches"],
		proNo : "LC27HG70QQNXZA",
		availability : "In Stock",
		detail : {
			"Rate" : "4.91",
			"Brand name" : "Sam sung",
			"Item Weight" : "15 pounds",
			"Product Dimensions" : "24.5 x 15.2 x 21.7 inches",
			"Item model number" : "LC27HG70QQNXZA",
			"Screen Size" : "49 inches",
			"Screen Resolution" : "2560 x 1440 pixels",
			Color : "Dark Blue Black(Matt)",
			Asin : "B06XSQ5QN8",
			"Shipping Weight" : "20.9 pounds",
			"Date First Available" : "19 May 2017",
		}	
	},
	{
		type : "display",
		name : "Sam sung C32H711 Curved Gaming Monitor",
		brand : "Sam sung",
		cost : "378.67",
		img : ["image/Sam sung C32H711 Curved Gaming Monitor.jpg","image/Sam sung C32H711 Curved Gaming Monitor2.jpg","image/Sam sung C32H711 Curved Gaming Monitor3.jpg"],
		info : ["Quantum Dot Color (sRGB 125%)","Clean Back Design (Concealed Cables)","3-sided Bezel-less Display. Brightness : 300cd/m2","NOTE: Refer the User Manual and the User Guide from the Technical Specification before use which is highly recommended."],		
		proNo : "LC32H711QENXZA",
		availability : "In Stock",
		detail : {
			"Rate" : "4.91",
			"Brand name" : "Sam sung",
			"Item Weight" : "15 pounds",
			"Product Dimensions" : "28.7 x 12.9 x 21.6 inches",
			"Item model number" : "LC32H711QENXZA",
			"Screen Size" : "32 inches",
			"Screen Resolution" : "2560 x 1440 pixels",
			Color : "White",
			Asin : "B06XT67BR7",
			"Shipping Weight" : "20.8 pounds",
			"Date First Available" : "21 May 2017",
		}	
	},
	// scanners
	{
		type : "scanners",
		name : "Canon CanoScan LiDE220 scanner",
		brand : "Canon",
		cost : "78.67",
		img : ["image/Canon CanoScan LiDE220 scanner.jpg","image/Canon CanoScan LiDE220 scanner2.jpg","image/Canon CanoScan LiDE220 scanner3.jpg"],
		info : ["Auto Scan Mode automatically adjusts settings by detecting what you are scanning","Scan a letter-sized document in approx. 10 seconds","Auto Document Fix automatically employs area-by-area correction for beautiful, easy-to-view scans"],
		proNo : "LiDE220",
		availability : "In Stock",
		detail : {
			"Rate" : "4.71",
			"Brand name" : "Canon",
			"Item Weight" : "3.5 pounds",
			"Product Dimensions" : "9.9 x 14.4 x 1.6 inches",
			"Item model number" : "LiDE220",
			"Wattage" : "2.5 watts",
			"Power Source" : "USB",
			"Software Included	" : "Ja",
			Asin : "B00LN0NUGC",
			"Shipping Weight" : "5.8 pounds",
			"Date First Available" : "21 May 2014",
		}	
	},
	{
		type : "scanners",
		name : "Canon CanoScan Mark II Scanner",
		brand : "Canon",
		cost : "78.67",
		img : ["image/Canon CanoScan Mark II Scanner.jpg","image/Canon CanoScan Mark II Scanner2.jpg","image/Canon CanoScan Mark II Scanner3.jpg"],
		info : ["Professional film, photo, slide and document scanner","High quality scanning: 9600x9600dpi for film, 4800x4800dpi for photos and documents","Fast photo and document scanning: approx. 7 sec for A4 colour at 300 dpi","High speed film scanning: approx. 18 sec for 35mm negative at 1200 dpi"],
		proNo : "6218B008AA",
		availability : "In Stock",
		detail : {
			"Rate" : "4.81",
			"Brand name" : "Canon",
			"Item Weight" : "4.6 kg",
			"Product Dimensions" : "48 x 11.1 x 27 cm",
			"Item model number" : "6218B008AA",
			"Wattage" : "15 watts",
			"Power Source" : "USB",
			"Software Included	" : "Ja",
			Asin : "B00LN0NUGC",
			"Shipping Weight" : "6.3 kg",
			"Date First Available" : "21 May 2013",
		}	
	},
	{
		type : "scanners",
		name : "Canon PIXMA All-In-One Scanner",
		brand : "Canon",
		cost : "24.99",
		img : ["image/Canon PIXMA All-In-One Scanner.jpg","image/Canon PIXMA All-In-One Scanner2.jpg","image/Canon PIXMA All-In-One Scanner3.jpg"],
		info : ["Compact and affordable all-in-one colour printer, scanner and copier","Optional XL ink cartridges for improved economy","Fast photo and document scanning: approx. 7 sec for A4 colour at 300 dpi","High speed film scanning: approx. 18 sec for 35mm negative at 1200 dpi"],
		proNo : "PIXMA MG2550S",
		availability : "In Stock",
		detail : {
			"Rate" : "4.51",
			"Brand name" : "Canon",
			"Item Weight" : "3.6 kg",
			"Product Dimensions" : "42.6 x 14.5 x 30.6 cm",
			"Item model number" : "PIXMA MG2550S",
			"Wattage" : "11 watts",
			"Power Source" : "AC 240V",
			"Software Included	" : "Ja",
			Asin : "B01J3B3HJW",
			"Shipping Weight" : "4.6 kg",
			"Date First Available" : "21 July 2016",
		}	
	},
	{
		type : "scanners",
		name : "Canon P-208II Mobile Scanner",
		brand : "Canon",
		cost : "24.99",
		img : ["image/Canon P-208II Mobile Scanner.jpg","image/Canon P-208II Mobile Scanner2.jpg","image/Canon P-208II Mobile Scanner3.jpg"],
		info : ["Ultra-compact, lightweight and versatile","Productive 16 ipm double-sided scanning with ten sheet ADF","Supports embossed card and photo scanning","Convenient, intuitive plug-and-scan operation"],
		proNo : "imageFORMULA",
		availability : "In Stock",
		detail : {
			"Rate" : "4.91",
			"Brand name" : "Canon",
			"Item Weight" : "0.59 kg",
			"Product Dimensions" : "31.2 x 8.9 x 4 cm",
			"Item model number" : "imageFORMULA",
			"Wattage" : "2.5 watts",
			"Power Source" : "USB",
			"Software Included	" : "Ja",
			Asin : "B00SOL9SFU",
			"Shipping Weight" : "0.9 kg",
			"Date First Available" : "21 Dec 2014",
		}	
	},
	// modems
	{
		type : "modems",
		name : "TP-Link 300 Mbps Wireless modems",
		brand : "TP-Link",
		cost : "19.46",
		img : ["image/TP-Link 300 Mbps Wireless modems.jpg","image/TP-Link 300 Mbps Wireless modems2.jpg","image/TP-Link 300 Mbps Wireless modems3.jpg"],
		info : ["Wireless N speed - 300 Mbps Wi-Fi speed meets your daily internet needs","Easy bandwidth management treaming","Fast encryption - one-touch WPA wireless security encryption with the WPS button. Compatible with IPv6 -the more recent Internet Protocol version","Parental controls and guest network"],
		proNo : "TL-WR841N",
		availability : "In Stock",
		detail : {
			"Rate" : "4.82",
			"Brand name" : "TP-Link",
			"Item Weight" : "0.97 kg",
			"Product Dimensions" : "13 x 3.3 x 19.3 cm",
			"Item model number" : "TL-WR841N",
			"Wattage" : "8 watts",
			"Processor Count" : "1",
			"Connectivity Type" : "802_11_ABGN",
			Color : "White",
			Asin : "B001FWYGJS",
			"Shipping Weight" : "1.9 kg",
			"Date First Available" : "21 Dec 2013",
		}	
	},
	{
		type : "modems",
		name : "TP-Link Wireless VDSL/ADSL modems",
		brand : "TP-Link",
		cost : "34.99",
		img : ["image/TP-Link Wireless.jpg","image/TP-Link Wireless2.jpg","image/TP-Link Wireless3.jpg"],
		info : ["All-in-one: VDSL2/ADSL2+ modem, NAT router and wireless access point in one device provides","Wireless and speed up to 300 Mbps","USB Port for storage sharing, printer sharing, FTP server, media server and UMTS/LTE (3G/4G) modem sharing"],
		proNo : "TL-WR841N",
		availability : "In Stock",
		detail : {
			"Rate" : "4.82",
			"Brand name" : "TP-Link",
			"Item Weight" : "0.67 kg",
			"Product Dimensions" : "26 x 23 x 7 cm",
			"Item model number" : "TD-W9970(UK)",
			"Wattage" : "8.2 watts",
			"Processor Count" : "1",
			"Connectivity Type" : "Wi-Fi",
			Color : "White",
			Asin : "B001FWY12O",
			"Shipping Weight" : "0.9 kg",
			"Date First Available" : "12 Dec 2016",
		}	
	},
	{
		type : "modems",
		name : "TP-LINK AC1600 modems",
		brand : "TP-Link",
		cost : "60.99",
		img : ["image/TP-LINK AC1600 modems.jpg","image/TP-LINK AC1600 modems2.jpg","image/TP-LINK AC1600 modems3.jpg"],
		info : ["Improved wireless speed - combined wireless speeds of up to 300 Mbps (over 2.4 GHz) and 1300 Mbps (over 5 GHz)","Versatile connectivity - with DSL, EWAN and USB ports","Blazing fast wired performance - connecting an external drive the USB 2.0 port allows you to share files, photos, music and video with any device on the network"],
		proNo : "ARCHER VR600 V2",
		availability : "Available from these sellers",
		detail : {
			"Rate" : "4.32",
			"Brand name" : "TP-Link",
			"Item Weight" : "0.39 kg",
			"Product Dimensions" : "21.6 x 16.4 x 2.6 cm",
			"Item model number" : "ARCHER VR600 V2",
			"Wattage" : "8.7 watts",
			"Processor Count" : "2",
			"Connectivity Type" : "Wi-Fi",
			Color : "Black",
			Asin : "B039FWY12O",
			"Shipping Weight" : "0.92 kg",
			"Date First Available" : "12 Dec 2016",
		}	
	},
	{
		type : "modems",
		name : "TP-LINK AC1750 modems",
		brand : "TP-Link",
		cost : "68.69",
		img : ["image/TP-LINK AC1750 modems.jpg","image/TP-LINK AC1750 modems2.jpg","image/TP-LINK AC1750 modems3.jpg"],
		info : ["Supports 802.11ac standard - the next generation of Wi-Fi","Simultaneous 2.4GHz 450Mbps ","Guest network access provides secure Wi-Fi access for guests sharing your home or office network. NOTE: Random version(version 1 or 2) will be sent as per the availability.","Built-in rechargeable battery provides hours of fun"],
		proNo : "FBA_Archer C7(UK)",
		availability : "Available from these sellers",
		detail : {
			"Rate" : "4.92",
			"Brand name" : "TP-Link",
			"Item Weight" : "0.622 kg",
			"Product Dimensions" : "21.6 x 16.4 x 2.6 cm",
			"Item model number" : "FBA_Archer C7(UK)",
			"Wattage" : "7.7 watts",
			"Processor Count" : "4",
			"Connectivity Type" : "Wi-Fi",
			Color : "Black",
			Asin : "B929FWY12O",
			"Shipping Weight" : "0.72 kg",
			"Date First Available" : "12 Dec 2013",
		}	
	},
	// graphic card
	{
		type : "graphic card",
		name : "ASUS AMD R5 graphic card",
		brand : "Asus",
		cost : "41.97",
		img : ["image/ASUS AMD R5 graphic card.jpg","image/ASUS AMD R5 graphic card2.jpg","image/ASUS AMD R5 graphic card3.jpg"],
		info : ["Silent passive cooling means true 0dB- perfect for quiet home theatre PCs and multimedia centers.","Lowers graphics card EMI by 66% for more stable operation, clearer display, and safer computing.","Low profile graphics cards for HTPC and multimedia PCs support smooth 1280 x 1024 gaming and Blu-ray 3D!"],
		proNo : "R5230-SL-2GD3-L",
		availability : "Available from these sellers",
		detail : {
			"Rate" : "4.92",
			"Brand name" : "Asus",
			"Item Weight" : "0.82 kg",
			"Product Dimensions" : "20 x 10 x 6 cm",
			"Item model number" : "R5230-SL-2GD3-L",
			"Wattage" : "7.7 watts",
			"Graphics Coprocessor": "Radeon",
			"Graphics Card Description" : "AMD Radeon R5 230",
			"Graphics Card Ram Size" : "2GB",
			"Graphics Card Interface" : "PCI-E",
			Color : "Black,Red",
			Asin : "B00K09XCII",
			"Shipping Weight" : "0.92 kg",
			"Date First Available" : "5 May 2014",
		}	
	},
	{
		type : "graphic card",
		name : "ASUS GT710-SL-2GD5 graphic card",
		brand : "Asus",
		cost : "40.49",
		img : ["image/ASUS GT710-SL-2GD5 graphic card.jpg","image/ASUS GT710-SL-2GD5 graphic card2.jpg","image/ASUS GT710-SL-2GD5 graphic card3.jpg"],
		info : ["Silent passive cooling means true 0dB - perfect for quiet home theatre PCs and multimedia centres.","Super Alloy Power Uses premium alloy components to reinforce overall graphics card reliability.","Industry only AUTO-EXTREME Technology,100% full automation for best reliability."],
		proNo : "R5230-SL-2GD3-L",
		availability : "Available from these sellers",
		detail : {
			"Rate" : "4.92",
			"Brand name" : "Asus",
			"Item Weight" : "0.399 kg",
			"Product Dimensions" : "16.7 x 1.7 x 6.9 cm",
			"Item model number" : "GT710-SL-2GD5",
			"Wattage" : "7.7 watts",
			"Graphics Coprocessor": "GeForce",
			"Graphics Card Description" : "NVIDIA GeForce GT 710",
			"Graphics Card Ram Size" : "2MB",
			"Graphics Card Interface" : "PCI-E",
			Color : "Black",
			Asin : "B07489XSJP",
			"Shipping Weight" : "0.492 kg",
			"Date First Available" : "8 Aug. 2017",
		}	
	},
	{
		type : "graphic card",
		name : "MSI GeForce GT 710 graphic card",
		brand : "MSI",
		cost : "40.78",
		img : ["image/MSI GeForce GT 710 graphic card.jpg","image/MSI GeForce GT 710 graphic card2.jpg","image/MSI GeForce GT 710 graphic card3.jpg"],
		info : ["10 years ultra-long lifetime (under full load). Lower temperature and higher efficiency.","Large heat sink covers the area of GPU and memory. Providing the best environment for gaming and multimedia.","Low profile design saves more spaces. User can build slim or smaller system easier"],
		proNo : "V809-2000R",
		availability : "In Stock",
		detail : {
			"Rate" : "4.92",
			"Brand name" : "Asus",
			"Item Weight" : "0.399 kg",
			"Product Dimensions" : "16.7 x 1.7 x 6.9 cm",
			"Item model number" : "V809-2000R",
			"Wattage" : "30 watts",
			"Graphics Coprocessor": "GeForce",
			"Graphics Card Description" : "NVIDIA GeForce GT 710",
			"Graphics Card Ram Size" : "2048 MB",
			"Graphics Card Interface" : "PCI-E",
			Color : "Black",
			Asin : "B01AY78MLM",
			"Shipping Weight" : "0.44 kg",
			"Date First Available" : "28 Aug. 2016",
		}	
	},
	{
		type : "graphic card",
		name : "MSI NVIDIA GeForce graphic card",
		brand : "MSI",
		cost : "110.78",
		img : ["image/MSI NVIDIA GeForce graphic card.jpg","image/MSI NVIDIA GeForce graphic card2.jpg","image/MSI NVIDIA GeForce graphic card3.jpg"],
		info : ["Ultimate GAMING: TWIN FROZR VI","TORX 2.0 FAN: Supremely silent","LED control / Mobile APP","NVIDIA GPU Boost 2.0 / NVIDIA Adaptive V-Sync / NVIDIA PhysX ready / NVIDIA 3D Vision Surround Ready / PCIE 3.0"],
		proNo : "V335-001R",
		availability : "In Stock",
		detail : {
			"Rate" : "4.92",
			"Brand name" : "Asus",
			"Item Weight" : "0.526 kg",
			"Product Dimensions" : "21 x 4 x 12 cm",
			"Item model number" : "V335-001R",
			"Wattage" : "15 watts",
			"Graphics Coprocessor": "Nvidia",
			"Graphics Card Description" : "MSI NVIDIA GeForce GTX 1050 Ti GAMING X 4G",
			"Graphics Card Ram Size" : "4 MB",
			"Graphics Card Interface" : "PCI-E",
			Color : "Black",
			Asin : "B01MAZ357B",
			"Shipping Weight" : "1.24 kg",
			"Date First Available" : "28 OCt. 2016",
		}	
	}

]

